//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Bottin_DetR.Models
{
    #region Contextes

    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class DatabaseEntities : ObjectContext
    {
        #region Constructeurs

        /// <summary>
        /// Initialise un nouvel objet DatabaseEntities à l'aide de la chaîne de connexion trouvée dans la section 'DatabaseEntities' du fichier de configuration d'application.
        /// </summary>
        public DatabaseEntities()
            : base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialisez un nouvel objet DatabaseEntities.
        /// </summary>
        public DatabaseEntities(string connectionString)
            : base(connectionString, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialisez un nouvel objet DatabaseEntities.
        /// </summary>
        public DatabaseEntities(EntityConnection connection)
            : base(connection, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        #endregion

        #region Méthodes partielles

        partial void OnContextCreated();

        #endregion

        #region Propriétés ObjectSet

        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<etudiant> table_etudiant
        {
            get
            {
                if ((_table_etudiant == null))
                {
                    _table_etudiant = base.CreateObjectSet<etudiant>("table_etudiant");
                }
                return _table_etudiant;
            }
        }
        private ObjectSet<etudiant> _table_etudiant;

        #endregion

        #region Méthodes AddTo

        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet table_etudiant. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTotable_etudiant(etudiant etudiant)
        {
            base.AddObject("table_etudiant", etudiant);
        }

        #endregion


         #region Méthodes EditTo

        public void EditTotable_etudiant(etudiant etudiant)
        {
           base.AcceptAllChanges();
           
        }

        #endregion
        }


        #endregion

        #region Entités

        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmEntityTypeAttribute(NamespaceName = "DatabaseModel", Name = "etudiant")]
        [Serializable()]
        [DataContractAttribute(IsReference = true)]
        public partial class etudiant : EntityObject
        {
            #region Méthode de fabrique

            /// <summary>
            /// Créez un nouvel objet etudiant.
            /// </summary>
            /// <param name="matricule">Valeur initiale de la propriété matricule.</param>
            /// <param name="prenom">Valeur initiale de la propriété prenom.</param>
            /// <param name="nom">Valeur initiale de la propriété nom.</param>
            /// <param name="annee_bac">Valeur initiale de la propriété annee_bac.</param>
            /// <param name="courriel">Valeur initiale de la propriété courriel.</param>
            /// <param name="mot_passe">Valeur initiale de la propriété mot_passe.</param>
            public static etudiant Createetudiant(global::System.String matricule, global::System.String prenom, global::System.String nom, global::System.Int32 annee_bac, global::System.String courriel, global::System.String mot_passe)
            {
                etudiant etudiant = new etudiant();
                etudiant.matricule = matricule;
                etudiant.prenom = prenom;
                etudiant.nom = nom;
                etudiant.annee_bac = annee_bac;
                etudiant.courriel = courriel;
                etudiant.mot_passe = mot_passe;
                return etudiant;
            }

            #endregion
            #region Propriétés primitives

            /// <summary>
            /// Aucune documentation sur les métadonnées n'est disponible.
            /// </summary>
            [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
            [DataMemberAttribute()]
            public global::System.String matricule
            {
                get
                {
                    return _matricule;
                }
                set
                {
                    if (_matricule != value)
                    {
                        OnmatriculeChanging(value);
                        ReportPropertyChanging("matricule");
                        _matricule = StructuralObject.SetValidValue(value, false);
                        ReportPropertyChanged("matricule");
                        OnmatriculeChanged();
                    }
                }
            }
            private global::System.String _matricule;
            partial void OnmatriculeChanging(global::System.String value);
            partial void OnmatriculeChanged();

            /// <summary>
            /// Aucune documentation sur les métadonnées n'est disponible.
            /// </summary>
            [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
            [DataMemberAttribute()]
            public global::System.String prenom
            {
                get
                {
                    return _prenom;
                }
                set
                {
                    OnprenomChanging(value);
                    ReportPropertyChanging("prenom");
                    _prenom = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("prenom");
                    OnprenomChanged();
                }
            }
            private global::System.String _prenom;
            partial void OnprenomChanging(global::System.String value);
            partial void OnprenomChanged();

            /// <summary>
            /// Aucune documentation sur les métadonnées n'est disponible.
            /// </summary>
            [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
            [DataMemberAttribute()]
            public global::System.String nom
            {
                get
                {
                    return _nom;
                }
                set
                {
                    OnnomChanging(value);
                    ReportPropertyChanging("nom");
                    _nom = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nom");
                    OnnomChanged();
                }
            }
            private global::System.String _nom;
            partial void OnnomChanging(global::System.String value);
            partial void OnnomChanged();

            /// <summary>
            /// Aucune documentation sur les métadonnées n'est disponible.
            /// </summary>
            [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
            [DataMemberAttribute()]
            public global::System.Int32 annee_bac
            {
                get
                {
                    return _annee_bac;
                }
                set
                {
                    Onannee_bacChanging(value);
                    ReportPropertyChanging("annee_bac");
                    _annee_bac = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("annee_bac");
                    Onannee_bacChanged();
                }
            }
            private global::System.Int32 _annee_bac;
            partial void Onannee_bacChanging(global::System.Int32 value);
            partial void Onannee_bacChanged();

            /// <summary>
            /// Aucune documentation sur les métadonnées n'est disponible.
            /// </summary>
            [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
            [DataMemberAttribute()]
            public global::System.String courriel
            {
                get
                {
                    return _courriel;
                }
                set
                {
                    OncourrielChanging(value);
                    ReportPropertyChanging("courriel");
                    _courriel = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("courriel");
                    OncourrielChanged();
                }
            }
            private global::System.String _courriel;
            partial void OncourrielChanging(global::System.String value);
            partial void OncourrielChanged();

            /// <summary>
            /// Aucune documentation sur les métadonnées n'est disponible.
            /// </summary>
            [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
            [DataMemberAttribute()]
            public global::System.String mot_passe
            {
                get
                {
                    return _mot_passe;
                }
                set
                {
                    Onmot_passeChanging(value);
                    ReportPropertyChanging("mot_passe");
                    _mot_passe = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("mot_passe");
                    Onmot_passeChanged();
                }
            }
            private global::System.String _mot_passe;
            partial void Onmot_passeChanging(global::System.String value);
            partial void Onmot_passeChanged();

            #endregion

        }

        #endregion

    }

